apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gallerypack-storage
  namespace: gallerypack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gallerypack-appdata
  namespace: gallerypack
spec:  gh run list --limit 5

  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
