apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tus-buffering
  namespace: gallerypack
spec:
  buffering:
    maxRequestBodyBytes: 0
    memRequestBodyBytes: 0
    maxResponseBodyBytes: 0
    memResponseBodyBytes: 0
